### ISSUE TITLE
Compile error, OS_SHAREDCFG_VADDR is undefined

### ISSUE THREAD

**Issue by mind-overflow** [LumaTeam/Luma3DS#1465]
Luma3DS cannot compile because OS_SHAREDCFG_VADDR is undefined. This is caused by commit #[768e5](https://github.com/LumaTeam/Luma3DS/commit/768e587b76a3b007e845e04cef66102b888facba), that introduced Luma shared config.

The thrown error is the following:
```
In file included from /root/Luma3DS/sysmodules/loader/source/loader.c:7:
/root/Luma3DS/sysmodules/loader/source/loader.c: In function 'hbldrIs3dsxTitle':
/root/Luma3DS/sysmodules/loader/source/luma_shared_config.h:28:58: error: 'OS_SHAREDCFG_VADDR' undeclared (first use in this function)
   28 | #define Luma_SharedConfig ((volatile LumaSharedConfig *)(OS_SHAREDCFG_VADDR + 0x800))
      |                                                          ^~~~~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/loader/source/loader.c:97:12: note: in expansion of macro 'Luma_SharedConfig'
   97 |     return Luma_SharedConfig->use_hbldr && tid == Luma_SharedConfig->hbldr_3dsx_tid;
      |            ^~~~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/loader/source/luma_shared_config.h:28:58: note: each undeclared identifier is reported only once for each function it appears in
   28 | #define Luma_SharedConfig ((volatile LumaSharedConfig *)(OS_SHAREDCFG_VADDR + 0x800))
      |                                                          ^~~~~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/loader/source/loader.c:97:12: note: in expansion of macro 'Luma_SharedConfig'
   97 |     return Luma_SharedConfig->use_hbldr && tid == Luma_SharedConfig->hbldr_3dsx_tid;
      |            ^~~~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/loader/source/loader.c:98:1: error: control reaches end of non-void function [-Werror=return-type]
   98 | }
      | ^
```
If I try switching to the previous version of loader.c (prior to that commit), I get another error: OS_KernelConfig is also undefined.

```
In file included from /root/Luma3DS/sysmodules/pm/source/process_monitor.c:8:
/root/Luma3DS/sysmodules/pm/source/process_monitor.c: In function 'cleanupProcess':
/root/Luma3DS/sysmodules/pm/source/util.h:11:34: error: 'OS_KernelConfig' undeclared (first use in this function)
   11 | #define IS_N3DS                 (OS_KernelConfig->app_memtype >= 6) // APPMEMTYPE. Hacky but doesn't use APT
      |                                  ^~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/pm/source/process_monitor.c:32:13: note: in expansion of macro 'IS_N3DS'
   32 |         if (IS_N3DS && OS_KernelConfig->app_memtype == 6) {
      |             ^~~~~~~
/root/Luma3DS/sysmodules/pm/source/util.h:11:34: note: each undeclared identifier is reported only once for each function it appears in
   11 | #define IS_N3DS                 (OS_KernelConfig->app_memtype >= 6) // APPMEMTYPE. Hacky but doesn't use APT
      |                                  ^~~~~~~~~~~~~~~
/root/Luma3DS/sysmodules/pm/source/process_monitor.c:32:13: note: in expansion of macro 'IS_N3DS'
   32 |         if (IS_N3DS && OS_KernelConfig->app_memtype == 6) {
      |             ^~~~~~~
```

**Comment by oreo639** [comment]
There is a libctru update avaliable.
run:
`(dkp-)pacman -Syu`

Also, Luma targets the latest commit of libctru, not the latest release of libctru, but there haven't been any changes to libctru since the last release (which was a few days ago).

**Comment by mind-overflow** [comment]
This was the problem. I completely forgot to check for updates... How dumb.
Thanks!
